<?php

/**
 * Created by PhpStorm.
 * User: funmi
 * Date: 3/10/17
 * Time: 12:57 PM
 */
class FaceBook extends Base
{

    // facebook API Object
    protected $fb;

    // facebook API token
    protected $access_token;


    // check if an integration is configured
    public function isConfigured()
    {
        if (empty($this->options['api_key']) || empty($this->options['secret_key'])){
            return false;
        }
        return true;
    }

    // Return facebook API  object init with API Settings
    public function getFacebookLoginObj(){
        if (is_object($this->fb)){
            return $this->fb;
        }
        $fb = new \Facebook\Facebook([
            'app_id' => $this->options['api_key'],
            'app_secret' =>$this->options['secret_key'],
            'default_graph_version' => 'v2.2'
        ]);
        $this->fb = $fb;
        return $fb;
    }

    // return the list properties to serialise
    protected function getSerializers($skip = array())
    {
        $skip = [];
        return parent::getSerializers($skip); // TODO: Change the autogenerated stub
    }

    public function getFinalExtraInputs(){
        return array('code','state','error_code','error','error_reason','error_description');// TODO: Change the autogenerated stub
    }

    // return facebook login start auth
    public function getLoginStartUrl($redirectUrl)
    {
        $facebook = $this->getFacebookLoginObj();
        $helper = $this->getRedirectLoginHelper();
        $permissions = ['email'];
        $login_url = $helper->getLoginUrl($redirectUrl,$permissions);
        return $login_url;
    }

    public function completeLogin($extraInputs = array())
    {
        // TODO: Implement completeLogin() method.
    }

    public function getUserProfile()
    {
        // TODO: Implement getUserProfile() method.
    }
}